-- Create a table for habits
create table public.habits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  target_frequency int default 1 -- e.g., times per day
);

-- Create a table for habit logs (completions)
create table public.habit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  habit_id bigint references public.habits(id) on delete cascade not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  notes text
);

-- Enable Row Level Security (RLS)
alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;

-- Create policies (Allow all for anonymous for now, assuming single user app)
-- NOTE: identifying users by IP or device is tricky without auth.
-- For now, we will allow public read/write to get started easily,
-- BUT this is insecure for production.
create policy "Allow public access to habits"
on public.habits
for all
to anon
using (true)
with check (true);

create policy "Allow public access to habit_logs"
on public.habit_logs
for all
to anon
using (true)
with check (true);
