-- nukes and rebuilds
DROP TABLE IF EXISTS public.habit_logs;
DROP TABLE IF EXISTS public.habits;

CREATE TABLE public.habits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  frequency_type text DEFAULT 'daily',
  frequency_value int DEFAULT 1,
  frequency_days int[] DEFAULT '{}'
);

CREATE TABLE public.habit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  habit_id bigint references public.habits(id) on delete cascade not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- disable RLS completely
ALTER TABLE public.habits DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.habit_logs DISABLE ROW LEVEL SECURITY;

-- grant access
GRANT ALL ON TABLE public.habits TO anon;
GRANT ALL ON TABLE public.habit_logs TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
